/**
 * @license Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 * CKEditor 4 LTS ("Long Term Support") is available under the terms of the Extended Support Model.
 */

/* exported CKBUILDER_CONFIG */

var CKBUILDER_CONFIG = {
	skin: 'moono-lisa',
    preset: 'standard',
	ignore: [
		'bender.js',
		'bender.ci.js',
		'bender-runner.config.json',
		'.bender',
		'bender-err.log',
		'bender-out.log',
		'.circleci',
		'dev',
		'docs',
		'.DS_Store',
		'.editorconfig',
		'.gitignore',
		'.gitattributes',
		'.github',
		'gruntfile.js',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'less',
		'.mailmap',
		'.nvmrc',
		'node_modules',
		'package.json',
		'README.md',
		'tests'
	],
	plugins: {
        'a11yhelp' : 1,
		'autocomplete': 1,
		'basicstyles' : 1,
		'blockquote' : 1,
		'clipboard' : 1,
		'contextmenu' : 1,
		'elementspath' : 1,
		'emoji' : 1,
		'enterkey' : 1,
		'entities' : 1,
		'filebrowser' : 1,
		'floatingspace' : 1,
		'font' : 1,
		'format' : 1,
		'horizontalrule' : 1,
		'htmlwriter' : 1,
		'image' : 1,
		'indentlist' : 1,
		'justify' : 1,
		'link' : 1,
		'list' : 1,
		'magicline' : 1,
		'maximize' : 1,
		'mentions' : 1,
		'pastefromgdocs' : 1,
		'pastefromword' : 1,
		'pastetext' : 1,
		'pastetools' : 1,
		'removeformat' : 1,
		'resize' : 1,
		'showborders' : 1,
		'sourcearea' : 1,
		'specialchar' : 1,
		'stylescombo' : 1,
		'tab' : 1,
		'table' : 1,
		'tableresize' : 1,
		'tableselection' : 1,
		'tabletools' : 1,
		'toolbar' : 1,
		'undo' : 1,
		'uploadimage' : 1,
		'wysiwygarea' : 1
	},
    languages : {
        'en' : 1
    }
};
